version: '3.8'

services:
  web:
    build: .
    command: gunicorn --config gunicorn_config.py myproject.wsgi:application
    volumes:
      - .:/app
    expose:
      - "8000"
    env_file:
      - .env
    depends_on:
      - db

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - web

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: myproject
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

volumes:
  postgres_data:
